#apiVersion: v1
#kind: Compose
version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
#  postgres:
#    image: postgres:15-alpine
#    container_name: postgres
#    restart: always
#    network_mode: host
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: BenNa1402*
#      POSTGRES_DB: postgres
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: theanh2906/backend
    container_name: backend
    volumes:
      - type=bind,source=/home/theanh2906/Desktop/uploads:/uploads
    network_mode: host
    ports:
      - "8081:8081"
#    depends_on:
#      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: BenNa1402*
volumes:
  postgres-data:
