server:
  port: 8081
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    listener:
      simple:
        retry:
          enabled: false
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2.0
    template:
      retry:
        max-attempts: 3
        enabled: false
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        retry.backoff.ms: 100
    consumer:
      group-id: backend-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "*"
        session.timeout.ms: 30000
        heartbeat.interval.ms: 10000
    listener:
      ack-mode: manual_immediate
      concurrency: 3
      poll-timeout: 3000
  datasource:
    hikari:
      schema: public
    password: admin
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 740845971597-quolkmkd830njlgsl1cmpgk4q8pm5u5l.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:4200
            scope:
              - email
              - profile
  session:
    jdbc:
      initialize-schema: always
    store-type: jdbc
upload-folder: uploads