server:
  port: 8081
spring:
  datasource:
    hikari:
      schema: public
    password: BenNa1402*
    url: jdbc:postgresql://theanh2906.ddns.net:5432/postgres
    username: postgres
  flyway:
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        validator:
          apply_to_ddl: false
    show-sql: false
