server:
  port: 8081
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    listener:
      simple:
        retry:
          enabled: false
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2.0
    template:
      retry:
        max-attempts: 3
        enabled: false
  datasource:
    hikari:
      schema: public
    password: admin
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 740845971597-quolkmkd830njlgsl1cmpgk4q8pm5u5l.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:4200
            scope:
              - email
              - profile
  session:
    jdbc:
      initialize-schema: always
    store-type: jdbc
upload-folder: uploads